---
Name: goldfinch-date
---
SilverStripe\ORM\FieldType\DBDate:
  extensions:
    - Goldfinch\Date\Extensions\DBCarbonExtension

SilverStripe\ORM\FieldType\DBDatetime:
  extensions:
    - Goldfinch\Date\Extensions\DBCarbonExtension

SilverStripe\ORM\FieldType\DBTime:
  extensions:
    - Goldfinch\Date\Extensions\DBCarbonExtension
